### PR TITLE
Add Flipper Skylanders Keys Repo

### PR DESCRIPTION
**Pull request by V0lk3n**
As said into discussions, here is my PR for adding "Flipper Skylanders" Repository.

Thanks! :)

### CODE REVIEW

**Comment by djsime1** [comment]
I'm moving the link to the Notes & References section since it's more of a how-to than a universal dump.

**Comment by V0lk3n** [comment]
Basically its to get a dictionnary for nfc dictionnary attack, but as im adding "how" and some ressources and that can growth i agree ^^ did i close the pr and leave it in your hand?

**Comment by djsime1** [comment]
I'll take care of closing in once I merge it with others.

**Comment by djsime1** [comment]
Merged with latest commit.

**Comment by V0lk3n** [comment]
Thanks! :)

**Comment by djsime1** [comment]
Reopening so I can mark this as merged.

**Pull request merged**
