### PR TITLE
Add https://github.com/vmeurisse/flipperzero-plugins

### PR DESCRIPTION
**Pull request by vmeurisse**
This contains precompiled plugins for the official firmware

### CODE REVIEW

**Comment by djsime1** [comment]
Neato! Currently working on rewriting a bunch of FAQ questions so I'll get this merged after I'm done with that.

**Comment by RogueMaster** [comment]
Heads up, some of these will only work right with the firmware they were intended for. For example, my firmware has a random deed generation function not in Unleashed. I call it to grab a random deed type to attribute a gain in experience into. I suspect that an RM app in unleashed would likely cause a crash on any of the actions below (I have not tried to see if it would even run, crash, or just power through the error (haha)):
- - Dice First Roll for d20+ = sides on dice (i.e. Nat 20 on d20)
- - Dice First Roll for d20+ = sides on dice - 1 (+1 EXP) (i.e. 19 on d20)
- - Getting 2048 in 2048
- - Mouse Jacker Ducky Run
- - NRFSniffer Found Address
- - Stopwatch @ Alert
- - Tetris, Snake, or Flappy Bird Score For EXP
- - Zombiez for every 20 Zombie kills

**Comment by vmeurisse** [comment]
@RogueMaster Trust me, [I saw that](https://github.com/vmeurisse/flipperzero-plugins/commit/e0e64d022d312bd755c95a3707db1d7a0eaee4d7) ;)
This is why the description explicitly mention the official firmware.

If you load a fap on an incompatible firmware, the error is handled. Flipper will check major version from [api_symbols.csv](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/firmware/targets/f7/api_symbols.csv) before loading anything. If it doesn't match, the app isn't loaded (no icon in menu, error message when trying to open). If the major version is the same, the app will try to start but show an error message if some of the function used are missing from the firmware (you can use the logs to get the list).

**Comment by djsime1** [comment]
So as you all probably know, I'm working on a site called Aquarium to host things just like this. If you don't mind, I'm going to leave this PR unmerged until I can decide how to proceed with the site. I'll try to reach out to all the devs of those plugins, in addition to the once already in the repo, to see if I can get their permission to republish their work.

**Comment by UberGuidoZ** [comment]
The linked apps are _heavily_ out of date. @vmeurisse are you planning on updating them?

I have a more current collection [over here](https://github.com/UberGuidoZ/Flipper/tree/main/Applications), including more linked in the Official folder ReadMe.

**Comment by djsime1** [comment]
Closing in favor of #98.

**Review by Spinike — COMMENTED** [review]
READ

**Pull request closed without merging**
