### PR TITLE
Add awesome-flipperzero-pack

### PR DESCRIPTION
**Pull request by katlol**
I am getting a flipperzero soon and I wanted to get a pack of resources to download, so...
I made a "simple script" to download all files from awesome-flipperzero repo and put it in a zip file...

interested to hear your thoughts / if you think it'd be of any use!

ZIP files made by github actions and uploaded to releases, code licensed CC0

https://github.com/katlol/awesome-flipperzero-pack/releases/latest

### CODE REVIEW

**Comment by djsime1** [comment]
I moved the link to a card at the top of the Databases & Dumps section, what do you think of it?

**Comment by katlol** [comment]
@djsime1 this looks great! I can rebase and include just this on this branch, then it might look cleaner...

**Comment by katlol** [comment]
Actually, I will assume there is a reason these commits are here and leave you to handle the conflict. It looks to be simple enough to be done by the web UI.

**Comment by djsime1** [comment]
Sorry, I pushed my working branch to your repo instead of the main branch. I'll handle this PR manually in the next update.

**Pull request merged**
