### PR TITLE
Added flipper app browser

### PR DESCRIPTION
**Pull request by electromuis**
Created an application that automatically lists all Flipper apps from github. The browsers let's you search through all these and can build them on demand when downloading.

### CODE REVIEW

**Comment by djsime1** [comment]
Really nice work on the website! How does get the list of repositories?

**Comment by electromuis** [comment]
It searches through GitHub (using the search code api) for application.fam files, happens in this file: https://github.com/electromuis/flipper-appbrowser/blob/main/backend/search.py

**Comment by djsime1** [comment]
Tentatively planning on merging once the site is working again.

**Comment by matdombrock** [comment]
@electromuis There is some kind of issue with your JSON data and the site isn't working right now. Is this a known issue?

**Comment by djsime1** [comment]
Closing this due the inclusion of the official app store in its place.

**Pull request closed without merging**
