### PR TITLE
Update Flipper zero Plugin Tutorial

### PR DESCRIPTION
**Pull request by TQMatvey**
Use the mfulz's fork as DroomOne's is completely outdated and doesnt work

### CODE REVIEW

**Comment by djsime1** [comment]
Thanks! I was waiting for someone to do this.

**Comment by TQMatvey** [comment]
@djsime1 So will you merge this PR..?

**Comment by djsime1** [comment]
I literally cloned it locally to prepare it for merging 30 seconds ago, it'll be done very soon.

**Comment by djsime1** [comment]
Merged into latest update.

**Comment by djsime1** [comment]
Reopening so I can mark this as merged.

**Comment by djsime1** [comment]
Nevermind I didn't realize you deleted your branch!

**Pull request closed without merging**
