### PR TITLE
Add flipperzero-bruteforce to Databases & Dumps

### PR DESCRIPTION
**Pull request by tobiabocchi**
I created a python script to generate brute force `.sub` files for potentially any known fixed code OOK protocol. I plan to add more protocols in the near future and think this might be a good starting point to unify more brute force applications under one single repo.

### CODE REVIEW

**Comment by djsime1** [comment]
Merged with latest update, thanks!

**Comment by Magnifico84** [comment]
Ciao Tobia! Can you tell me how install the files into the flipper? sorry but i'm a novice.

**Comment by tobiabocchi** [comment]
Just copy them onto your sd card inside subghz folder

**Comment by Magnifico84** [comment]
Thank you so much Tobia.

**Comment by djsime1** [comment]
Reopening so I can mark this as merged.

**Pull request merged**
